# Updated in: 2023-12-01
jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: 8569b893b1c124cad6b28931919ed99e69423920
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: bbf2f8bcfae6f08a248e5e415a4f6d8be2c14f33
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  latest_verified_commit: 7d6de00cd57c46916c6d8b12124a6c9600ed31d4
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: 4e2ce5163e686fc1049d0ba4a5f26a1dc96e9a77
  mode: git-clone
t5x:
  url: https://github.com/google-research/t5x.git
  mirror_url: https://github.com/nvjax-svc-0/t5x.git
  tracking_ref: main
  latest_verified_commit: dcbe3e7a4c4849939d8bb3549df8d674b72075e3
  mode: git-clone
  patches:
    mirror/patch/partial-checkpoint-restore: file://patches/t5x/mirror-patch-partial-checkpoint-restore.patch # pull/1392/head  # https://github.com/google-research/t5x/pull/1392: Add support for partial checkpoint restore
    mirror/patch/dali-support: file://patches/t5x/mirror-patch-dali-support.patch # pull/1393/head  # https://github.com/google-research/t5x/pull/1393: Adds DALI support to t5x
    mirror/patch/t5x_te_in_contrib_noindent: file://patches/t5x/mirror-patch-t5x_te_in_contrib_noindent.patch # pull/1391/head  # https://github.com/google-research/t5x/pull/1391: Adds transformer engine support and GPU optimizations to T5x (enables H100)
paxml:
  url: https://github.com/google/paxml.git
  mirror_url: https://github.com/nvjax-svc-0/paxml.git
  tracking_ref: main
  latest_verified_commit: e5bebb78635d042b1212703d3a31d81ca61ca2fa
  mode: git-clone
  patches:
    pull/46/head: file://patches/paxml/PR-46.patch # adds Transformer Engine support
praxis:
  url: https://github.com/google/praxis.git
  mirror_url: https://github.com/nvjax-svc-0/praxis.git
  tracking_ref: main
  latest_verified_commit: 61943c1f6430bac01f4bf112c7a952a434eb82cc
  mode: git-clone
  patches:
    pull/27/head: file://patches/praxis/PR-27.patch # This PR allows XLA:GPU to detect the MHA pattern more easily to call fused kernels from cublas.
    pull/36/head: file://patches/praxis/PR-36.patch # adds Transformer Engine support
lingvo:
  # Used only in ARM pax builds
  url: https://github.com/tensorflow/lingvo.git
  tracking_ref: master
  latest_verified_commit: 05a076b0783a8bbf4a770095966c472bb37bbf65
  mode: git-clone
tensorflow-text:
  # Used only in ARM pax builds
  url: https://github.com/tensorflow/text.git
  tracking_ref: v2.13.0
  latest_verified_commit: 917a681d7220ebf9b62a08b6f9ce7b7db886ddef
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
# Used by praxis
fiddle:
  url: https://github.com/google/fiddle.git
  tracking_ref: main
  latest_verified_commit: 2a17618c56eb99aa58aa898ae12cbac7cf5c3b30
  mode: pip-vcs
# Used by t5x
airio:
  url: https://github.com/google/airio.git
  tracking_ref: main
  latest_verified_commit: 6137bc84c0368a46d33fb63c50aa99c51697181b
  mode: pip-vcs
clu:
  url: https://github.com/google/CommonLoopUtils.git
  tracking_ref: main
  latest_verified_commit: eed40a1facd526df0e0faa192525f357a3321dca
  mode: pip-vcs
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0540a43971f4a8a16693a9de9de73c1072020769
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 6a57d35539f5193a9756a7cb846654e9b221b2e7
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: 2e92d570c784de4b357dce83180021e658a9210f
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: 452d83524791222ed741caaa911cff31e481adc6
  mode: pip-vcs
# used by Pallas
openxla-triton:
  url: https://github.com/openxla/triton.git
  tracking_ref: llvm-head
  latest_verified_commit: e16a58f8ab87278985c51b4936c5703a5bdb950d
  mode: git-clone
jax-triton:
  url: https://github.com/jax-ml/jax-triton.git
  tracking_ref: main
  latest_verified_commit: e308f5def7a4f7581a24a682cde6a145b8ac8d16
  mode: git-clone
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: 10a7c473e9feb1107894e7588b283b1bcfcbd679
  mode: git-clone
